var dir_2534fabef37d53a9be799c6b35cbe4e0 =
[
    [ "average.cuh", "average_8cuh.html", null ],
    [ "average.h", "backend_2average_8h.html", null ],
    [ "creation.cuh", "creation_8cuh.html", null ],
    [ "cusp_matrix_blas.cuh", "cusp__matrix__blas_8cuh.html", "cusp__matrix__blas_8cuh" ],
    [ "cusp_precon_blas.h", "cusp__precon__blas_8h.html", null ],
    [ "cusp_thrust_backend.h", "cusp__thrust__backend_8h.html", null ],
    [ "cusp_vector_blas.h", "cusp__vector__blas_8h.html", [
      [ "VectorTraits< cusp::array1d< T, M > >", "structdg_1_1_vector_traits_3_01cusp_1_1array1d_3_01_t_00_01_m_01_4_01_4.html", "structdg_1_1_vector_traits_3_01cusp_1_1array1d_3_01_t_00_01_m_01_4_01_4" ]
    ] ],
    [ "derivatives.h", "derivatives_8h.html", "derivatives_8h" ],
    [ "derivativesX.h", "derivatives_x_8h.html", "derivatives_x_8h" ],
    [ "dlt.h", "dlt_8h.html", [
      [ "DLT", "classdg_1_1_d_l_t.html", "classdg_1_1_d_l_t" ]
    ] ],
    [ "dx.h", "dx_8h.html", "dx_8h" ],
    [ "dx_matrix_blas.cuh", "dx__matrix__blas_8cuh.html", "dx__matrix__blas_8cuh" ],
    [ "dxmatrix_traits.h", "dxmatrix__traits_8h.html", null ],
    [ "dxX.h", "dx_x_8h.html", "dx_x_8h" ],
    [ "ell_interpolation.cuh", "ell__interpolation_8cuh.html", "ell__interpolation_8cuh" ],
    [ "evaluation.cuh", "evaluation_8cuh.html", "evaluation_8cuh" ],
    [ "evaluationX.cuh", "evaluation_x_8cuh.html", "evaluation_x_8cuh" ],
    [ "functions.h", "functions_8h.html", "functions_8h" ],
    [ "grid.h", "grid_8h.html", null ],
    [ "gridX.h", "grid_x_8h.html", null ],
    [ "interpolation.cuh", "interpolation_8cuh.html", "interpolation_8cuh" ],
    [ "interpolationX.cuh", "interpolation_x_8cuh.html", "interpolation_x_8cuh" ],
    [ "matrix_categories.h", "matrix__categories_8h.html", [
      [ "AnyMatrixTag", "structdg_1_1_any_matrix_tag.html", null ],
      [ "CuspMatrixTag", "structdg_1_1_cusp_matrix_tag.html", null ],
      [ "SelfMadeMatrixTag", "structdg_1_1_self_made_matrix_tag.html", null ],
      [ "dx_matrixTag", "structdg_1_1dx__matrix_tag.html", null ],
      [ "MPIMatrixTag", "structdg_1_1_m_p_i_matrix_tag.html", null ],
      [ "ThrustMatrixTag", "structdg_1_1_thrust_matrix_tag.html", null ],
      [ "CuspPreconTag", "structdg_1_1_cusp_precon_tag.html", null ],
      [ "MPIPreconTag", "structdg_1_1_m_p_i_precon_tag.html", null ]
    ] ],
    [ "matrix_traits.h", "matrix__traits_8h.html", null ],
    [ "matrix_traits_thrust.h", "matrix__traits__thrust_8h.html", null ],
    [ "mpi_collective.h", "mpi__collective_8h.html", null ],
    [ "mpi_derivatives.h", "mpi__derivatives_8h.html", "mpi__derivatives_8h" ],
    [ "mpi_evaluation.h", "mpi__evaluation_8h.html", "mpi__evaluation_8h" ],
    [ "mpi_grid.h", "mpi__grid_8h.html", null ],
    [ "mpi_init.h", "mpi__init_8h.html", "mpi__init_8h" ],
    [ "mpi_matrix.h", "mpi__matrix_8h.html", null ],
    [ "mpi_matrix_blas.h", "mpi__matrix__blas_8h.html", null ],
    [ "mpi_precon.h", "mpi__precon_8h.html", "mpi__precon_8h" ],
    [ "mpi_precon_blas.h", "mpi__precon__blas_8h.html", null ],
    [ "mpi_vector.h", "mpi__vector_8h.html", "mpi__vector_8h" ],
    [ "mpi_vector_blas.h", "mpi__vector__blas_8h.html", null ],
    [ "operator.h", "operator_8h.html", "operator_8h" ],
    [ "operator_tensor.cuh", "operator__tensor_8cuh.html", "operator__tensor_8cuh" ],
    [ "projection.cuh", "projection_8cuh.html", "projection_8cuh" ],
    [ "selfmade_blas.cuh", "selfmade__blas_8cuh.html", "selfmade__blas_8cuh" ],
    [ "sparseblockmat.cuh", "sparseblockmat_8cuh.html", null ],
    [ "sparseblockmat.h", "sparseblockmat_8h.html", null ],
    [ "sparseblockmat_gpu_kernels.cuh", "sparseblockmat__gpu__kernels_8cuh.html", "sparseblockmat__gpu__kernels_8cuh" ],
    [ "sparseblockmat_omp_kernels.h", "sparseblockmat__omp__kernels_8h.html", "sparseblockmat__omp__kernels_8h" ],
    [ "std_matrix_blas.cuh", "std__matrix__blas_8cuh.html", null ],
    [ "std_vector_blas.cuh", "std__vector__blas_8cuh.html", null ],
    [ "tensor.cuh", "tensor_8cuh.html", "tensor_8cuh" ],
    [ "thrust_matrix_blas.cuh", "thrust__matrix__blas_8cuh.html", null ],
    [ "thrust_vector_blas.cuh", "thrust__vector__blas_8cuh.html", null ],
    [ "timer.cuh", "timer_8cuh.html", null ],
    [ "topological_traits.h", "topological__traits_8h.html", [
      [ "MPITag", "structdg_1_1_m_p_i_tag.html", null ],
      [ "SharedTag", "structdg_1_1_shared_tag.html", null ],
      [ "OneDimensionalTag", "structdg_1_1_one_dimensional_tag.html", null ],
      [ "TwoDimensionalTag", "structdg_1_1_two_dimensional_tag.html", null ],
      [ "ThreeDimensionalTag", "structdg_1_1_three_dimensional_tag.html", null ]
    ] ],
    [ "transpose.h", "transpose_8h.html", null ],
    [ "typedefs.cuh", "typedefs_8cuh.html", "typedefs_8cuh" ],
    [ "vector_categories.h", "vector__categories_8h.html", [
      [ "AnyVectorTag", "structdg_1_1_any_vector_tag.html", null ],
      [ "StdVectorTag", "structdg_1_1_std_vector_tag.html", null ],
      [ "ThrustVectorTag", "structdg_1_1_thrust_vector_tag.html", null ],
      [ "CuspVectorTag", "structdg_1_1_cusp_vector_tag.html", null ],
      [ "MPIVectorTag", "structdg_1_1_m_p_i_vector_tag.html", null ]
    ] ],
    [ "vector_traits.h", "vector__traits_8h.html", null ],
    [ "weights.cuh", "weights_8cuh.html", "weights_8cuh" ],
    [ "weightsX.cuh", "weights_x_8cuh.html", "weights_x_8cuh" ],
    [ "xspacelib.cuh", "xspacelib_8cuh.html", "xspacelib_8cuh" ]
];