var dir_5b85b054eaae83068f60d9ca3773e17d =
[
    [ "adaption.h", "adaption_8h.html", null ],
    [ "average.h", "average_8h.html", null ],
    [ "conformal.h", "conformal_8h.html", null ],
    [ "curvilinear.h", "curvilinear_8h.html", null ],
    [ "curvilinearX.h", "curvilinear_x_8h.html", null ],
    [ "flux.h", "flux_8h.html", null ],
    [ "geometries.h", "geometries_8h.html", null ],
    [ "guenther.h", "guenther_8h.html", null ],
    [ "guenther_parameters.h", "guenther__parameters_8h.html", null ],
    [ "hector.h", "hector_8h.html", null ],
    [ "init.h", "init_8h.html", null ],
    [ "magnetic_field.h", "magnetic__field_8h.html", null ],
    [ "mpi_conformal.h", "mpi__conformal_8h.html", null ],
    [ "mpi_curvilinear.h", "mpi__curvilinear_8h.html", null ],
    [ "mpi_geometries.h", "mpi__geometries_8h.html", null ],
    [ "mpi_orthogonal.h", "mpi__orthogonal_8h.html", null ],
    [ "orthogonal.h", "orthogonal_8h.html", null ],
    [ "orthogonalX.h", "orthogonal_x_8h.html", null ],
    [ "refined_conformal.h", "refined__conformal_8h.html", null ],
    [ "refined_curvilinear.h", "refined__curvilinear_8h.html", null ],
    [ "refined_orthogonal.h", "refined__orthogonal_8h.html", null ],
    [ "refined_orthogonalX.h", "refined__orthogonal_x_8h.html", null ],
    [ "ribeiro.h", "ribeiro_8h.html", null ],
    [ "ribeiroX.h", "ribeiro_x_8h.html", null ],
    [ "separatrix_orthogonal.h", "separatrix__orthogonal_8h.html", null ],
    [ "simple_orthogonal.h", "simple__orthogonal_8h.html", null ],
    [ "solovev.h", "solovev_8h.html", null ],
    [ "solovev_doc.h", "solovev__doc_8h.html", null ],
    [ "solovev_parameters.h", "solovev__parameters_8h.html", null ],
    [ "taylor.h", "taylor_8h.html", "taylor_8h" ],
    [ "testfunctors.h", "testfunctors_8h.html", null ],
    [ "utilities.h", "utilities_8h.html", null ],
    [ "utilitiesX.h", "utilities_x_8h.html", "utilities_x_8h" ]
];