var hierarchy =
[
    [ "aBinaryOperator", "structa_binary_operator.html", null ],
    [ "aContainer", "structa_container.html", null ],
    [ "aGenerator", "structa_generator.html", null ],
    [ "aGeneratorX", "structa_generator_x.html", null ],
    [ "dg::geo::Alpha< MagneticField >", "structdg_1_1geo_1_1_alpha.html", null ],
    [ "aTokamakMagneticField", "structa_tokamak_magnetic_field.html", null ],
    [ "dg::geo::BHatP< MagneticField >", "structdg_1_1geo_1_1_b_hat_p.html", null ],
    [ "dg::geo::BHatR< MagneticField >", "structdg_1_1geo_1_1_b_hat_r.html", null ],
    [ "dg::geo::BHatZ< MagneticField >", "structdg_1_1geo_1_1_b_hat_z.html", null ],
    [ "dg::geo::Bmodule< MagneticField >", "structdg_1_1geo_1_1_bmodule.html", null ],
    [ "dg::geo::BR< MagneticField >", "structdg_1_1geo_1_1_b_r.html", null ],
    [ "dg::geo::BZ< MagneticField >", "structdg_1_1geo_1_1_b_z.html", null ],
    [ "dg::geo::CurvatureKappaR", "structdg_1_1geo_1_1_curvature_kappa_r.html", null ],
    [ "dg::geo::CurvatureKappaZ< MagneticField >", "structdg_1_1geo_1_1_curvature_kappa_z.html", null ],
    [ "dg::geo::CurvatureNablaBR< MagneticField >", "structdg_1_1geo_1_1_curvature_nabla_b_r.html", null ],
    [ "dg::geo::CurvatureNablaBZ< MagneticField >", "structdg_1_1geo_1_1_curvature_nabla_b_z.html", null ],
    [ "dg::geo::DeltaFunction< MagneticField >", "structdg_1_1geo_1_1_delta_function.html", null ],
    [ "dg::geo::DivCurvatureKappa< MagneticField >", "structdg_1_1geo_1_1_div_curvature_kappa.html", null ],
    [ "dg::geo::DivLiseikinX< PsiX, PsiY, PsiXX, PsiXY, PsiYY >", "structdg_1_1geo_1_1_div_liseikin_x.html", null ],
    [ "dg::geo::DivLiseikinY< PsiX, PsiY, PsiXX, PsiXY, PsiYY >", "structdg_1_1geo_1_1_div_liseikin_y.html", null ],
    [ "dg::geo::Field< MagneticField >", "structdg_1_1geo_1_1_field.html", null ],
    [ "dg::geo::FieldP< MagneticField >", "structdg_1_1geo_1_1_field_p.html", null ],
    [ "dg::geo::FieldR< MagneticField >", "structdg_1_1geo_1_1_field_r.html", null ],
    [ "dg::geo::FieldT< MagneticField >", "structdg_1_1geo_1_1_field_t.html", null ],
    [ "dg::geo::FieldZ< MagneticField >", "structdg_1_1geo_1_1_field_z.html", null ],
    [ "dg::geo::FluxGenerator< Psi, PsiX, PsiY, PsiXX, PsiXY, PsiYY, Ipol, IpolX, IpolY >", "structdg_1_1geo_1_1_flux_generator.html", null ],
    [ "dg::geo::FluxSurfaceAverage< MagneticField, container >", "structdg_1_1geo_1_1_flux_surface_average.html", null ],
    [ "dg::geo::GaussianDamping< Psi >", "structdg_1_1geo_1_1_gaussian_damping.html", null ],
    [ "dg::geo::GaussianProfDamping< Psi >", "structdg_1_1geo_1_1_gaussian_prof_damping.html", null ],
    [ "dg::geo::GaussianProfXDamping< Psi >", "structdg_1_1geo_1_1_gaussian_prof_x_damping.html", null ],
    [ "dg::geo::solovev::GeomParameters", "structdg_1_1geo_1_1solovev_1_1_geom_parameters.html", null ],
    [ "dg::geo::guenther::GeomParameters", "structdg_1_1geo_1_1guenther_1_1_geom_parameters.html", null ],
    [ "dg::geo::GradLnB< MagneticField >", "structdg_1_1geo_1_1_grad_ln_b.html", null ],
    [ "dg::Grid2d", "../../../inc/dg/html/structdg_1_1_grid2d.html", [
      [ "dg::ConformalGrid2d< container >", "structdg_1_1_conformal_grid2d.html", null ],
      [ "dg::CurvilinearGrid2d< container >", "structdg_1_1_curvilinear_grid2d.html", null ],
      [ "dg::OrthogonalGrid2d< container >", "structdg_1_1_orthogonal_grid2d.html", null ],
      [ "dg::RefinedGrid2d", "../../../inc/dg/html/structdg_1_1_refined_grid2d.html", [
        [ "dg::ConformalRefinedGrid2d< container >", "structdg_1_1_conformal_refined_grid2d.html", null ],
        [ "dg::CurvilinearRefinedGrid2d< container >", "structdg_1_1_curvilinear_refined_grid2d.html", null ],
        [ "dg::OrthogonalRefinedGrid2d< container >", "structdg_1_1_orthogonal_refined_grid2d.html", null ]
      ] ]
    ] ],
    [ "dg::Grid3d", "../../../inc/dg/html/structdg_1_1_grid3d.html", [
      [ "dg::ConformalGrid3d< container >", "structdg_1_1_conformal_grid3d.html", null ],
      [ "dg::CurvilinearGrid3d< container >", "structdg_1_1_curvilinear_grid3d.html", null ],
      [ "dg::OrthogonalGrid3d< container >", "structdg_1_1_orthogonal_grid3d.html", null ],
      [ "dg::RefinedGrid3d", "../../../inc/dg/html/structdg_1_1_refined_grid3d.html", [
        [ "dg::ConformalRefinedGrid3d< container >", "structdg_1_1_conformal_refined_grid3d.html", null ],
        [ "dg::CurvilinearRefinedGrid3d< container >", "structdg_1_1_curvilinear_refined_grid3d.html", null ],
        [ "dg::OrthogonalRefinedGrid3d< container >", "structdg_1_1_orthogonal_refined_grid3d.html", null ]
      ] ]
    ] ],
    [ "dg::GridX2d", "../../../inc/dg/html/structdg_1_1_grid_x2d.html", [
      [ "dg::CurvilinearGridX2d< container >", "structdg_1_1_curvilinear_grid_x2d.html", null ],
      [ "dg::OrthogonalGridX2d< container >", "structdg_1_1_orthogonal_grid_x2d.html", null ],
      [ "dg::RefinedGridX2d", "../../../inc/dg/html/structdg_1_1_refined_grid_x2d.html", [
        [ "dg::OrthogonalRefinedGridX2d< container >", "structdg_1_1_orthogonal_refined_grid_x2d.html", null ]
      ] ]
    ] ],
    [ "dg::GridX3d", "../../../inc/dg/html/structdg_1_1_grid_x3d.html", [
      [ "dg::CurvilinearGridX3d< container >", "structdg_1_1_curvilinear_grid_x3d.html", null ],
      [ "dg::OrthogonalGridX3d< container >", "structdg_1_1_orthogonal_grid_x3d.html", null ],
      [ "dg::RefinedGridX3d", "../../../inc/dg/html/structdg_1_1_refined_grid_x3d.html", [
        [ "dg::OrthogonalRefinedGridX3d< container >", "structdg_1_1_orthogonal_refined_grid_x3d.html", null ]
      ] ]
    ] ],
    [ "dg::geo::Hector< IMatrix, Matrix, container >", "structdg_1_1geo_1_1_hector.html", null ],
    [ "dg::geo::InvB< MagneticField >", "structdg_1_1geo_1_1_inv_b.html", null ],
    [ "dg::geo::taylor::Ipol", "structdg_1_1geo_1_1taylor_1_1_ipol.html", null ],
    [ "dg::geo::guenther::Ipol", "structdg_1_1geo_1_1guenther_1_1_ipol.html", null ],
    [ "dg::geo::solovev::Ipol", "structdg_1_1geo_1_1solovev_1_1_ipol.html", null ],
    [ "dg::geo::taylor::IpolR", "structdg_1_1geo_1_1taylor_1_1_ipol_r.html", null ],
    [ "dg::geo::guenther::IpolR", "structdg_1_1geo_1_1guenther_1_1_ipol_r.html", null ],
    [ "dg::geo::solovev::IpolR", "structdg_1_1geo_1_1solovev_1_1_ipol_r.html", null ],
    [ "dg::geo::taylor::IpolZ", "structdg_1_1geo_1_1taylor_1_1_ipol_z.html", null ],
    [ "dg::geo::guenther::IpolZ", "structdg_1_1geo_1_1guenther_1_1_ipol_z.html", null ],
    [ "dg::geo::solovev::IpolZ", "structdg_1_1geo_1_1solovev_1_1_ipol_z.html", null ],
    [ "dg::geo::Iris< Psi >", "structdg_1_1geo_1_1_iris.html", null ],
    [ "dg::geo::solovev::LaplacePsip", "structdg_1_1geo_1_1solovev_1_1_laplace_psip.html", null ],
    [ "dg::geo::taylor::LaplacePsip", "structdg_1_1geo_1_1taylor_1_1_laplace_psip.html", null ],
    [ "dg::geo::guenther::LaplacePsip", "structdg_1_1geo_1_1guenther_1_1_laplace_psip.html", null ],
    [ "dg::geo::Liseikin_XX< PsiX, PsiY >", "structdg_1_1geo_1_1_liseikin___x_x.html", null ],
    [ "dg::geo::Liseikin_XY< PsiX, PsiY >", "structdg_1_1geo_1_1_liseikin___x_y.html", null ],
    [ "dg::geo::Liseikin_YY< PsiX, PsiY >", "structdg_1_1geo_1_1_liseikin___y_y.html", null ],
    [ "dg::geo::LiseikinCollective< PsiX, PsiY, PsiXX, PsiXY, PsiYY >", "structdg_1_1geo_1_1_liseikin_collective.html", null ],
    [ "dg::geo::LnB< MagneticField >", "structdg_1_1geo_1_1_ln_b.html", null ],
    [ "dg::geo::solovev::MagneticField", "structdg_1_1geo_1_1solovev_1_1_magnetic_field.html", null ],
    [ "dg::geo::guenther::MagneticField", "structdg_1_1geo_1_1guenther_1_1_magnetic_field.html", null ],
    [ "dg::geo::taylor::MagneticField", "structdg_1_1geo_1_1taylor_1_1_magnetic_field.html", null ],
    [ "dg::MPIGrid2d", "../../../inc/dg/html/structdg_1_1_m_p_i_grid2d.html", [
      [ "dg::ConformalMPIGrid2d< LocalContainer >", "structdg_1_1_conformal_m_p_i_grid2d.html", null ],
      [ "dg::CurvilinearMPIGrid2d< LocalContainer >", "structdg_1_1_curvilinear_m_p_i_grid2d.html", null ],
      [ "dg::OrthogonalMPIGrid2d< LocalContainer >", "structdg_1_1_orthogonal_m_p_i_grid2d.html", null ]
    ] ],
    [ "dg::MPIGrid3d", "../../../inc/dg/html/structdg_1_1_m_p_i_grid3d.html", [
      [ "dg::ConformalMPIGrid3d< LocalContainer >", "structdg_1_1_conformal_m_p_i_grid3d.html", null ],
      [ "dg::CurvilinearMPIGrid3d< LocalContainer >", "structdg_1_1_curvilinear_m_p_i_grid3d.html", null ],
      [ "dg::OrthogonalMPIGrid3d< LocalContainer >", "structdg_1_1_orthogonal_m_p_i_grid3d.html", null ]
    ] ],
    [ "dg::geo::NablaPsiInv< PsiX, PsiY >", "structdg_1_1geo_1_1_nabla_psi_inv.html", null ],
    [ "dg::geo::NablaPsiInvCollective< PsiX, PsiY, PsiXX, PsiXY, PsiYY >", "structdg_1_1geo_1_1_nabla_psi_inv_collective.html", null ],
    [ "dg::geo::NablaPsiInvX< PsiX, PsiY, PsiXX, PsiXY, PsiYY >", "structdg_1_1geo_1_1_nabla_psi_inv_x.html", null ],
    [ "dg::geo::NablaPsiInvY< PsiX, PsiY, PsiXX, PsiXY, PsiYY >", "structdg_1_1geo_1_1_nabla_psi_inv_y.html", null ],
    [ "dg::geo::Nprofile< Psi >", "structdg_1_1geo_1_1_nprofile.html", null ],
    [ "dg::geo::PsiLimiter< Psi >", "structdg_1_1geo_1_1_psi_limiter.html", null ],
    [ "dg::geo::taylor::Psip", "structdg_1_1geo_1_1taylor_1_1_psip.html", null ],
    [ "dg::geo::guenther::Psip", "structdg_1_1geo_1_1guenther_1_1_psip.html", null ],
    [ "dg::geo::solovev::Psip", "structdg_1_1geo_1_1solovev_1_1_psip.html", null ],
    [ "dg::geo::taylor::PsipR", "structdg_1_1geo_1_1taylor_1_1_psip_r.html", null ],
    [ "dg::geo::solovev::PsipR", "structdg_1_1geo_1_1solovev_1_1_psip_r.html", null ],
    [ "dg::geo::guenther::PsipR", "structdg_1_1geo_1_1guenther_1_1_psip_r.html", null ],
    [ "dg::geo::guenther::PsipRR", "structdg_1_1geo_1_1guenther_1_1_psip_r_r.html", null ],
    [ "dg::geo::taylor::PsipRR", "structdg_1_1geo_1_1taylor_1_1_psip_r_r.html", null ],
    [ "dg::geo::solovev::PsipRR", "structdg_1_1geo_1_1solovev_1_1_psip_r_r.html", null ],
    [ "dg::geo::solovev::PsipRZ", "structdg_1_1geo_1_1solovev_1_1_psip_r_z.html", null ],
    [ "dg::geo::guenther::PsipRZ", "structdg_1_1geo_1_1guenther_1_1_psip_r_z.html", null ],
    [ "dg::geo::taylor::PsipRZ", "structdg_1_1geo_1_1taylor_1_1_psip_r_z.html", null ],
    [ "dg::geo::PsiPupil< Psi >", "structdg_1_1geo_1_1_psi_pupil.html", null ],
    [ "dg::geo::taylor::PsipZ", "structdg_1_1geo_1_1taylor_1_1_psip_z.html", null ],
    [ "dg::geo::solovev::PsipZ", "structdg_1_1geo_1_1solovev_1_1_psip_z.html", null ],
    [ "dg::geo::guenther::PsipZ", "structdg_1_1geo_1_1guenther_1_1_psip_z.html", null ],
    [ "dg::geo::solovev::PsipZZ", "structdg_1_1geo_1_1solovev_1_1_psip_z_z.html", null ],
    [ "dg::geo::taylor::PsipZZ", "structdg_1_1geo_1_1taylor_1_1_psip_z_z.html", null ],
    [ "dg::geo::guenther::PsipZZ", "structdg_1_1geo_1_1guenther_1_1_psip_z_z.html", null ],
    [ "dg::geo::Pupil< Psi >", "structdg_1_1geo_1_1_pupil.html", null ],
    [ "dg::geo::Ribeiro< Psi, PsiX, PsiY, PsiXX, PsiXY, PsiYY >", "structdg_1_1geo_1_1_ribeiro.html", null ],
    [ "dg::geo::RibeiroFluxGenerator< Psi, PsiX, PsiY, PsiXX, PsiXY, PsiYY >", "structdg_1_1geo_1_1_ribeiro_flux_generator.html", null ],
    [ "dg::geo::RibeiroX< Psi, PsiX, PsiY, PsiXX, PsiXY, PsiYY >", "structdg_1_1geo_1_1_ribeiro_x.html", null ],
    [ "dg::geo::SafetyFactor< MagneticField, container >", "structdg_1_1geo_1_1_safety_factor.html", null ],
    [ "dg::geo::SeparatrixOrthogonal< Psi, PsiX, PsiY, LaplacePsi >", "structdg_1_1geo_1_1_separatrix_orthogonal.html", null ],
    [ "dg::geo::SimpleOrthogonal< Psi, PsiX, PsiY, LaplacePsi >", "structdg_1_1geo_1_1_simple_orthogonal.html", null ],
    [ "dg::geo::SimpleOrthogonalX< Psi, PsiX, PsiY, LaplacePsi >", "structdg_1_1geo_1_1_simple_orthogonal_x.html", null ],
    [ "dg::geo::TanhSource< Psi >", "structdg_1_1geo_1_1_tanh_source.html", null ],
    [ "dg::geo::ZonalFlow< Psi >", "structdg_1_1geo_1_1_zonal_flow.html", null ]
];